services:
  mysql-image:
    container_name: Database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: abcdefgh
    volumes:
      - ./mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    
  backend:
    build:
      context: ./backend 
    ports:
       - "4000:4000"
    volumes:
      - ./backend:/app
    depends_on:
      mysql-image:
        condition: service_healthy
    restart: on-failure
    command: node index.js

  frontend:
    build:
        context: ./frontend
    ports:
        - "3000:3000"
    volumes:
        - ./frontend:/app
    environment:
      - NODE_ENV=production
    command: npm start


